In [1]:
from neural_flow import bijectors  as b
from neural_flow import bijectors2  as b2
import jax
from jax import numpy as jnp
import numpy as np
from pprint import pprint

In [2]:
rngkey = jax.random.PRNGKey(0)

x = jnp.array(np.random.default_rng(0).uniform(size=12) * 10  - 1.2).reshape(-1, 3)
c = jnp.array(np.random.default_rng(0).uniform(size=x.shape[0] * 2) * 10  - 1.2).reshape(-1, 2)

params, forward, inverse = b.ShiftBounds(x.min(axis=0), x.max(axis=0), 6)[0](rngkey, x.shape[1])

m = b2.ShiftBounds(6)
params2 = m.init(rngkey, x, x)

print(x)
print(*forward(params, x))
print(*m.forward(params, x, x))
print(*inverse(params, x))
print(*m.inverse(params, x, x))

[[ 5.1696167  1.4978671 -0.7902648]
 [-1.0347236  6.9327025  7.9275556]
 [ 4.866358   6.0949655  4.23625  ]
 [ 8.150724   6.9585357 -1.172615 ]]
[[ 2.1054387 -6.        -5.4958115]
 [-6.         5.9432306  6.       ]
 [ 1.7092569  4.102276   1.1324356]
 [ 6.         6.        -6.       ]] [1.3312352 1.3312352 1.3312352 1.3312352]
[[ 2.1054385 -6.        -5.495812 ]
 [-6.         5.943231   6.       ]
 [ 1.7092569  4.102276   1.1324356]
 [ 6.         6.        -6.       ]] [1.3312352 1.3312352 1.3312352 1.3312352]
[[7.5151043 4.9098144 2.7781749]
 [2.765967  7.382967  9.389313 ]
 [7.2829733 7.00175   6.5900197]
 [9.797005  7.394723  2.4882205]] [-1.3312352 -1.3312352 -1.3312352 -1.3312352]
[[7.5151043 4.9098144 2.7781749]
 [2.765967  7.382967  9.389312 ]
 [7.2829733 7.00175   6.5900197]
 [9.797005  7.394723  2.4882207]] [-1.3312352 -1.3312352 -1.3312352 -1.3312352]


In [3]:
params, forward, inverse = b.Roll(2)[0](rngkey, x.shape[1])

pprint(x)

pprint(forward(params, x))
pprint(inverse(params, x))

m = b2.Roll(2)
params = m.init(rngkey, x, x)

pprint(m.forward(params, x, x))
pprint(m.inverse(params, x, x))

Array([[ 5.1696167,  1.4978671, -0.7902648],
       [-1.0347236,  6.9327025,  7.9275556],
       [ 4.866358 ,  6.0949655,  4.23625  ],
       [ 8.150724 ,  6.9585357, -1.172615 ]], dtype=float32)
(Array([[ 1.4978671, -0.7902648,  5.1696167],
       [ 6.9327025,  7.9275556, -1.0347236],
       [ 6.0949655,  4.23625  ,  4.866358 ],
       [ 6.9585357, -1.172615 ,  8.150724 ]], dtype=float32),
 Array([0., 0., 0., 0.], dtype=float32))
(Array([[-0.7902648,  5.1696167,  1.4978671],
       [ 7.9275556, -1.0347236,  6.9327025],
       [ 4.23625  ,  4.866358 ,  6.0949655],
       [-1.172615 ,  8.150724 ,  6.9585357]], dtype=float32),
 Array([0., 0., 0., 0.], dtype=float32))
(Array([[ 1.4978671, -0.7902648,  5.1696167],
       [ 6.9327025,  7.9275556, -1.0347236],
       [ 6.0949655,  4.23625  ,  4.866358 ],
       [ 6.9585357, -1.172615 ,  8.150724 ]], dtype=float32),
 Array([0., 0., 0., 0.], dtype=float32))
(Array([[-0.7902648,  5.1696167,  1.4978671],
       [ 7.9275556, -1.0347236,  6.932702

In [4]:
params, forward, inverse = b.NeuralSplineCoupling(n_conditions=c.shape[1])[0](rngkey, x.shape[1])

m = b2.NeuralSplineCoupling()
params2 = m.init(rngkey, x, c)

pprint(x)
pprint(forward(params, x, conditions=c))
pprint(m.forward(params2, x, c))
pprint(inverse(params, x, conditions=c))
pprint(m.inverse(params2, x, c))

Array([[ 5.1696167,  1.4978671, -0.7902648],
       [-1.0347236,  6.9327025,  7.9275556],
       [ 4.866358 ,  6.0949655,  4.23625  ],
       [ 8.150724 ,  6.9585357, -1.172615 ]], dtype=float32)
(Array([[ 5.1696167,  4.275432 ,  1.5589511],
       [-1.0347236,  6.9327025,  7.9275556],
       [ 4.866358 ,  6.0949655,  4.999849 ],
       [ 8.150724 ,  6.9585357,  4.726246 ]], dtype=float32),
 Array([ -4.920542,   0.      , -18.03167 ,  -1.587937], dtype=float32))
(Array([[ 5.1696167,  4.275432 ,  1.5589511],
       [-1.0347236,  6.9327025,  7.9275556],
       [ 4.866358 ,  6.0949655,  4.999849 ],
       [ 8.150724 ,  6.9585357,  4.726246 ]], dtype=float32),
 Array([ -4.920542,   0.      , -18.03167 ,  -1.587937], dtype=float32))
(Array([[ 5.1696167 , -0.24028783, -3.3333778 ],
       [-1.0347236 ,  6.9327025 ,  7.9275556 ],
       [ 4.866358  ,  6.0949655 , -4.201853  ],
       [ 8.150724  ,  6.9585357 , -3.3949006 ]], dtype=float32),
 Array([-4.921891 , -0.       , -1.933465 , -5.02469

In [5]:
params, forward, inverse = b.RollingSplineCoupling(3, n_conditions=c.shape[1], hidden_layers=1, hidden_dim=4)[0](rngkey, x.shape[1])

m = b2.RollingSplineCoupling(3, hidden_layers=1, hidden_dim=4)
params2 = m.init(rngkey, x, c)

pprint(forward(params, x, conditions=c))
pprint(m.forward(params2, x, c))

pprint(inverse(params, x, conditions=c))
pprint(m.inverse(params2, x, c))


(Array([[ 5.1696167,  4.9973273,  1.2417324],
       [ 4.8839417,  6.9327025,  7.9275556],
       [-1.9824331,  6.0949655,  3.7173274],
       [ 8.150724 ,  6.9585357,  2.4464202]], dtype=float32),
 Array([-18.9669    , -37.12782   ,   0.08329237,  -1.8245347 ], dtype=float32))
(Array([[ 5.1696167,  4.9973273,  1.2417324],
       [ 4.8839417,  6.9327025,  7.9275556],
       [-1.9824331,  6.0949655,  3.7173274],
       [ 8.150724 ,  6.9585357,  2.4464202]], dtype=float32),
 Array([-18.9669    , -37.12782   ,   0.08329237,  -1.8245347 ], dtype=float32))
(Array([[ 5.1696167, -4.722045 , -2.730033 ],
       [-4.309967 ,  6.9327025,  7.9275556],
       [ 4.9831004,  6.0949655,  4.51068  ],
       [ 8.150724 ,  6.9585357, -4.625471 ]], dtype=float32),
 Array([ -7.253644 , -13.613178 ,  -6.5933785,  -3.2401614], dtype=float32))
(Array([[ 5.1696167, -4.722045 , -2.730033 ],
       [-4.309967 ,  6.9327025,  7.9275556],
       [ 4.9831004,  6.0949655,  4.51068  ],
       [ 8.150724 ,  6.9585357,